import type { Metadata } from "next";
import { Karla } from "next/font/google";
import "./globals.css";
import Nav from "@/components/ui/nav";
import { Toaster } from "@/components/ui/toaster";

const font = Karla({
	weight: ['700'],
	subsets: ['latin'],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${font.className} dark antialiased md:flex`}>
				<Nav />
				<div className="lg:px-20 md:pt-20 max-lg:p-4 w-full">
					{children}
				</div>
				<Toaster />
			</body>
		</html>
	);
}
